version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_bookstore_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: BookstoreApp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_bookstore
    environment:
      PGADMIN_DEFAULT_EMAIL: talpai.zsolt@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: